### ISSUE TITLE
[bug] first tab focus causes page scroll

### ISSUE THREAD

**Issue by petrklus** [Financial-Times/o-tabs#29]
When using o-tabs, the first tab always seems to get focus (and its ID is added to the URL). This causes page to scroll to the o-tabs location, which is unwanted.

I was also able to reproduce it in the demo.

**Comment by petrklus** [comment]
@AlbertoElias would you mind looking into this for us please?

**Comment by petrklus** [comment]
@AlbertoElias sorry for the bump, but here is one :)

**Comment by AlbertoElias** [comment]
Ah, sorry Petr. Is it ok if I look into this on Monday?

-- 

------------------------------

*This email was sent by a company owned by Financial Times Group Limited 
("FT Group <http://aboutus.ft.com/corporate-information/#axzz3rajCSIAt>"), 
registered office at Number One Southwark Bridge, London SE1 9HL.  
Registered in England and Wales with company number 879531. This e-mail may 
contain confidential information. If you are not the intended recipient, 
please notify the sender immediately, delete all copies and do not 
distribute it further.  It could also contain personal views which are not 
necessarily those of the FT Group.  We may monitor outgoing or 
incoming emails as permitted by law.*

**Comment by petrklus** [comment]
@AlbertoElias that would be amazing, thank you!

**Comment by alicebartlett** [comment]
(skim reading here, but this sounds related: https://github.com/Financial-Times/o-tabs/pull/17)

**Comment by AlbertoElias** [comment]
Yes, I think Alice is right. @petrklus  could you confirm if it works? If so, I'll merge the other pr

**Comment by petrklus** [comment]
Not sure @AlbertoElias - I am not using the selectTab directly (defining o-tabs via markup only) and the PR seems to be related to documentation only.

To sum up - when a page with o-tabs is loaded, it gets scrolled down to the first tab. I was able to reproduce it in the demo as well (which as far as I can see is not explicitly using selectTab either).

**Comment by jamesnicholls** [comment]
I experienced this issue recently. The `disableFocus` argument referenced in the documentation is no longer supported in the constructor or the static `init` method. I'm not sure when or why this was changed.

**Comment by AlbertoElias** [comment]
How's #30 ?

**Comment by petrklus** [comment]
@AlbertoElias does it use the disabledFocus by default when using markup to initialise?

**Comment by AlbertoElias** [comment]
What do you by using markup to initialise? It currently requires that you
set the disableFocus property to true manually

-- 

------------------------------

*This email was sent by a company owned by Financial Times Group Limited 
("FT Group <http://aboutus.ft.com/corporate-information/#axzz3rajCSIAt>"), 
registered office at Number One Southwark Bridge, London SE1 9HL.  
Registered in England and Wales with company number 879531. This e-mail may 
contain confidential information. If you are not the intended recipient, 
please notify the sender immediately, delete all copies and do not 
distribute it further.  It could also contain personal views which are not 
necessarily those of the FT Group.  We may monitor outgoing or 
incoming emails as permitted by law.*

**Comment by petrklus** [comment]
I mean I just use markup to get the o-tabs to initialise:
    
     <ul data-o-component="o-tabs" class="o-tabs" role="tablist" data-o-tabs-update-url="">

**Comment by AlbertoElias** [comment]
Do you mean you're using the build service?

**Comment by petrklus** [comment]
Yes, that's correct!

**Comment by AlbertoElias** [comment]
@petrklus I just pushed a new commit that allows you to set config options declaratively

**Comment by petrklus** [comment]
Still an issue on v2.3.0 @AlbertoElias. 

I am using something along the lines:

    <ul data-o-component="o-tabs" class="o-tabs" role="tablist" data-o-tabs-update-url="" data-o-tabs-disableFocus="true">

And I am still getting the focus & scroll on page load.

**Comment by petrklus** [comment]
still seems to be an issue with 2.3.1 @AlbertoElias

**Comment by AlbertoElias** [comment]
I've looked at the code running on that live site you sent me and it's still 2.3.0

**Comment by petrklus** [comment]
I tried 2.3.1 locally - but I've updated the preview link as well, still scrolling all the way down.
